"""Default configuration values."""

DEFAULT_DB_PATH = "./tailevents.db"

DEFAULT_LLM_BACKEND = "ollama"
DEFAULT_OLLAMA_BASE_URL = "http://100.115.45.10:11434"
DEFAULT_OLLAMA_MODEL = "qwen3:32b"
DEFAULT_CLAUDE_MODEL = "claude-sonnet-4-20250514"
DEFAULT_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
DEFAULT_OPENROUTER_MODEL = ""
DEFAULT_OPENROUTER_SITE_URL = None
DEFAULT_OPENROUTER_APP_NAME = None

DEFAULT_PROXY_URL = "http://127.0.0.1:7897"
DEFAULT_NO_PROXY_HOSTS = ["100.115.45.10"]

DEFAULT_API_HOST = "0.0.0.0"
DEFAULT_API_PORT = 8766

DEFAULT_RENAME_SIMILARITY_THRESHOLD = 0.8
DEFAULT_AST_PARSER = "python_ast"

DEFAULT_CACHE_ENABLED = True
DEFAULT_CACHE_DEFAULT_TTL = None

DEFAULT_EXPLANATION_MAX_EVENTS = 20
DEFAULT_EXPLANATION_TEMPERATURE = 0.3
DEFAULT_EXPLANATION_DETAILED_CONCURRENCY = 1
DEFAULT_EXPLANATION_STREAM_FLUSH_CHARS = 40
DEFAULT_EXPLANATION_STREAM_FLUSH_MS = 100
DEFAULT_EXPLANATION_STREAM_STALL_TIMEOUT_MS = 30_000

DEFAULT_SUMMARY_BACKEND = None
DEFAULT_SUMMARY_MODEL = None
DEFAULT_SUMMARY_MAX_TOKENS = None
DEFAULT_SUMMARY_TIMEOUT_MS = None
DEFAULT_DETAILED_BACKEND = None
DEFAULT_DETAILED_MODEL = None
DEFAULT_DETAILED_MAX_TOKENS = None
DEFAULT_DETAILED_TIMEOUT_MS = None

__all__ = [
    "DEFAULT_API_HOST",
    "DEFAULT_API_PORT",
    "DEFAULT_AST_PARSER",
    "DEFAULT_CACHE_DEFAULT_TTL",
    "DEFAULT_CACHE_ENABLED",
    "DEFAULT_CLAUDE_MODEL",
    "DEFAULT_DB_PATH",
    "DEFAULT_DETAILED_BACKEND",
    "DEFAULT_DETAILED_MAX_TOKENS",
    "DEFAULT_DETAILED_MODEL",
    "DEFAULT_DETAILED_TIMEOUT_MS",
    "DEFAULT_EXPLANATION_MAX_EVENTS",
    "DEFAULT_EXPLANATION_DETAILED_CONCURRENCY",
    "DEFAULT_EXPLANATION_STREAM_FLUSH_CHARS",
    "DEFAULT_EXPLANATION_STREAM_FLUSH_MS",
    "DEFAULT_EXPLANATION_STREAM_STALL_TIMEOUT_MS",
    "DEFAULT_EXPLANATION_TEMPERATURE",
    "DEFAULT_LLM_BACKEND",
    "DEFAULT_NO_PROXY_HOSTS",
    "DEFAULT_OPENROUTER_APP_NAME",
    "DEFAULT_OPENROUTER_BASE_URL",
    "DEFAULT_OPENROUTER_MODEL",
    "DEFAULT_OPENROUTER_SITE_URL",
    "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_OLLAMA_MODEL",
    "DEFAULT_PROXY_URL",
    "DEFAULT_RENAME_SIMILARITY_THRESHOLD",
    "DEFAULT_SUMMARY_BACKEND",
    "DEFAULT_SUMMARY_MAX_TOKENS",
    "DEFAULT_SUMMARY_MODEL",
    "DEFAULT_SUMMARY_TIMEOUT_MS",
]
